### ISSUE TITLE
Схема платы

### ISSUE THREAD

**Issue by Rastapa** [DCVostok/vostok-1-frmwrk-vn-arduino#1]
Добрый день. 
Получил вашу плату, не могу использовать пока не пойму как организованно  согласование с  напряжением 5 вольт. Не возможно использовать плату не зная схему (хотя бы преподаватель кружка должен знать). Прошу предоставить принципиальную схему.
Заранее сасибо.

**Comment by kenny5660** [comment]
Здравствуйте, пользовательская электрическая схема сейчас подготавливается, в ближайшее время появится в репозитории.

**Comment by kenny5660** [comment]
Схема платы добавлена в репозиторий [VOSTOK_UNO-VN035_circuit.pdf](https://github.com/DCVostok/vostok-1-frmwrk-vn-arduino/blob/main/doc/VOSTOK_UNO-VN035_circuit.pdf)
