### ISSUE TITLE
Работа с LCD экраном

### ISSUE THREAD

**Issue by Rechevik** [DCVostok/vostok-1-frmwrk-vn-arduino#2]
Добрый день. Не могу подключить экран типа HD44780, ни через i2с (с помощью указанной вами библиотеки [LiquidCrystal_I2C](https://github.com/enjoyneering/LiquidCrystal_I2C), ни через пины с использованием примеров для платы. Не могли бы вы привести пример работающего кода?

**Comment by kenny5660** [comment]
Здравствуйте, проверили работу LCD. Указанная нами библиотека [LiquidCrystal_I2C](https://github.com/enjoyneering/LiquidCrystal_I2C) обновилась до версии 1.3.3 и больше не совместима с нашей платой.
Поменяли библиотеку на [LCD_I2C](https://github.com/blackhack/LCD_I2C) и запустили такой код:
```
#include "Wire.h"
#include <LCD_I2C.h>

LCD_I2C lcd(0x27, 16, 2); // Default address of most PCF8574 modules is 0x27, PCF8574A has default address 0x3F 
void setup() {
  Serial.begin(115200);
  Wire.begin();
  lcd.begin();
  lcd.backlight();
}

void loop() {
  Serial.print("Vostok uno-vn035 LCD ");
  Serial.print("millis: ");
  Serial.println(millis());

  lcd.clear();
  lcd.setCursor(0, 0);
  lcd.print("Vostok uno-vn035 LCD");
  lcd.setCursor(0, 1);
  lcd.print("millis: ");
  lcd.print(millis());
  delay(200);
}
```

**Comment by Rechevik** [comment]
Спасибо, теперь заработало! Причем, только с модулем PCF8574AT, а с модулем PCF8574T - нет.

**Comment by kenny5660** [comment]
Разница между PCF8574AT и PCF8574T только в i2c адресе, попробуйте проверить все адреса

**Comment by Rechevik** [comment]
Проверил 0x27 и 0x3F.

**Comment by demsergey** [comment]
@Rechevik Здравствуйте, у вас получилось подключиться к модулю PCF8574T используя новую библиотеку?

**Comment by Rechevik** [comment]
> @Rechevik Здравствуйте, у вас получилось подключиться к модулю PCF8574T используя новую библиотеку?

Здравствуйте! Нет, остановился на PCF8574AT, для проекта пока этого достаточно)
